config/routes.rb
Rails.application.routes.draw do
  resources :solveds
  root 'main#welcome'
  post 'main/index'
  get 'main/index'
  get 'main/welcome'
  post 'main/welcome'

end

app/models/solved.rb
class Solved < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def last_solved
  	@last_solveds = Solved.all.order('created_at DESC')
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  	if request.post?
  		if params["restantes"].to_i>1
	  		@pokemons=eval(params["pokemones"])
	  		@pokemon=PokemonControl.new(@pokemons)
	  		answer = params["button"]
	  		opcion = params["opcion"]
	  		opciones = JSON.parse(cookies[:opciones])
		  	if answer =~ /yes/ and opcion.length > 1
		  		opciones << opcion
		  		cookies[:opciones] = JSON.generate(opciones)
		  	end
	  		numero_pregunta = params["numeroPregunta"].to_i
	  		case numero_pregunta
	  		when 0
	  			@pokemon.answerCanEvolve(answer)
	  		when 1
	  			@pokemon.answerNameQuestion(answer,opcion)
	  		when 2
	  			@pokemon.anwserMoveQuestion(answer,opcion)
	  		when 3
	  			@pokemon.answerTypeQuestion(answer,opcion)
	  		when 4
	  			@pokemon.answerColorQuestion(answer,opcion)
	  		when 5
	  			@pokemon.answerCharacteristicQuestion(answer,opcion)
	  		end
	  		@pokemons=@pokemon.obtenerPokemones
	  		@primeraPregunta = "1"
	  		banderita = 0
	  		while banderita == 0 do
	  			@siguientePregunta = @pokemon.siguientePregunta(@primeraPregunta)
	  			unless opciones =~ /#{@siguientePregunta[1]}/
	  				banderita = 1
	  			end
	  		end
	  		if @siguientePregunta[0] =~ /La primera/
		  		@numero_pregunta = "1"
		  	elsif @siguientePregunta[0] =~ /Puede aprender/
		  		@numero_pregunta = "2"
		  	elsif @siguientePregunta[0] =~ /Es de tipo/
		  		@numero_pregunta = "3"
		  	elsif @siguientePregunta[0] =~ /Puede evolucionar tu pokemon/
		  		@numero_pregunta = "0"
		  	elsif @siguientePregunta[0] =~ /Es de color/
		  		@numero_pregunta = "4"
		  	elsif @siguientePregunta[0] =~ /Tu pokemon es/
		  		@numero_pregunta = "5"
		  	end 
		  	@pregunta = @siguientePregunta.to_s.gsub(/\"|\[|\]|,/,"")
		  	@restantes = @pokemon.obtenerRestantes
	  	end
	  	if @restantes.to_i == 1
	  		s = Solved.new(name: "#{cookies[:name]}", pokemon: "ElPokemon")
	  		s.save!
	  	end
  	else
  		@pokemon=PokemonControl.new
  		@primeraPregunta = "0"
  		@siguientePregunta = @pokemon.siguientePregunta(@primeraPregunta)
  		if @siguientePregunta[0] =~ /La primera/
	  		@numero_pregunta = "1"
	  	elsif @siguientePregunta[0] =~ /Puede aprender/
	  		@numero_pregunta = "2"
	  	elsif @siguientePregunta[0] =~ /Es de tipo/
	  		@numero_pregunta = "3"
	  	elsif @siguientePregunta[0] =~ /Puede evolucionar tu pokemon/
	  		@numero_pregunta = "0"
	  	elsif @siguientePregunta[0] =~ /Es de color/
	  		@numero_pregunta = "4"
	  	elsif @siguientePregunta[0] =~ /Tu pokemon es/
	  		@numero_pregunta = "5"
	  	end 
	  	@pregunta = @siguientePregunta.to_s.gsub(/\"|\[|\]|,/,"")
	  	@restantes = @pokemon.obtenerRestantes
	  	opciones = ["evolve"]
	  	cookies[:opciones] = JSON.generate(opciones)

  	end  	 
  end
  def welcome
  	if request.post?
  		cookies[:nombre] = params["nombre"]
  		redirect_to :action => "index"
  	end	
  end
end

app/controllers/solveds_controller.rb
class SolvedsController < ApplicationController
  before_action :set_solved, only: [:show, :edit, :update, :destroy]

  # GET /solveds
  # GET /solveds.json
  def index
    @solveds = Solved.all
  end

  # GET /solveds/1
  # GET /solveds/1.json
  def show
  end

  # GET /solveds/new
  def new
    @solved = Solved.new
  end

  # GET /solveds/1/edit
  def edit
  end

  # POST /solveds
  # POST /solveds.json
  def create
    @solved = Solved.new(solved_params)

    respond_to do |format|
      if @solved.save
        format.html { redirect_to @solved, notice: 'Solved was successfully created.' }
        format.json { render :show, status: :created, location: @solved }
      else
        format.html { render :new }
        format.json { render json: @solved.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solveds/1
  # PATCH/PUT /solveds/1.json
  def update
    respond_to do |format|
      if @solved.update(solved_params)
        format.html { redirect_to @solved, notice: 'Solved was successfully updated.' }
        format.json { render :show, status: :ok, location: @solved }
      else
        format.html { render :edit }
        format.json { render json: @solved.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solveds/1
  # DELETE /solveds/1.json
  def destroy
    @solved.destroy
    respond_to do |format|
      format.html { redirect_to solveds_url, notice: 'Solved was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solved
      @solved = Solved.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solved_params
      params.require(:solved).permit(:name, :pokemon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def aTresDigitos(numero)
		numero = numero.to_s
		if numero.length == 1
			numero = '00'+numero
		elsif numero.length == 2
			numero = '0'+numero
		end
		return numero
	end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/solveds_helper.rb
module SolvedsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokemon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
  <footer>
  	<table>
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Pokemon</th>
	    </tr>
	  </thead>

	  <tbody>
	    <% Solved.all.order('created_at DESC').each do |solved| %>
	      <tr>
	        <td><%= solved.name %></td>
	        <td><%= solved.pokemon %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
  </footer>
</body>
</html>

app/views/main/index.html.erb
<h1>¿QUIÉN ES ESE POKEMÓN?</h1>
<%if @restantes.to_i != 0%>
	<h2 id="pregunta">¿<%=@pregunta%>?</h2>
<%else%>
	<h2 id="pregunta">No estoy seguro de cual es tu pokemon, ¿podemos volver a intentarlo?</h2>
<%end%>
<div id="botones">
	<%= form_tag(main_index_path, :method=>'post') do %>
	  <%unless @restantes.to_i == 1 or @restantes.to_i == 0%>
		  <%=image_submit_tag "btnSi.png", :name=>"button",:id=>"btnSi",:value=>"yes",:height => "100px"%>
  		  <%=image_submit_tag "btnIdk.png", :name=>"button",:id=>"btnNoSe",:value=>"idk"%>	
  		  <%=image_submit_tag "btnNo.png", :name=>"button",:id=>"btnNo",:value=>"no"%>
      <%end%>
	  <%=hidden_field_tag "opcion", "#{@siguientePregunta[1]}"%>
	  <%=hidden_field_tag "primeraPregunta", "#{@primeraPregunta.to_s}"%>
	  <%=hidden_field_tag "numeroPregunta", "#{@numero_pregunta}"%>
	  <%=hidden_field_tag "restantes", "#{@restantes}"%>
	  <%=hidden_field_tag "pokemones", "#{@pokemon.obtenerPokemones}"%>
	  <%if @restantes.to_i == 1%>
	  	<%numero_pokemon=eval(@pokemon.obtenerPokemones.to_s).first[0]%>
	  	<%=image_tag("#{aTresDigitos(numero_pokemon)}.png")%><br/>
	  	<input type="button" value="Jugar de nuevo" onClick="refrescar();">
	  <%elsif @restantes.to_i == 0%>
		<input type="button" value="Intentarlo de nuevo" onClick="refrescar();">
	  <%end%>
	<% end %>
</div>
<div class="centrado" id="datos">
	<h4 class="letraBlanca">Jugador: <%=cookies[:nombre]%></h4>
	<h4 class="letraBlanca">Restantes: <%=@restantes%></h4>
</div>
<script>
function refrescar(){
	 window.location.replace("http://192.168.192.128/main/index");
 }
</script>

app/views/main/welcome.html.erb
<h1> BIENVENIDO </h1>
<h2 class="letraBlanca centrado"> Antes de comenzar a jugar, dime cual es tu nombre </h2>
<div id="botones">
	<%= form_tag(main_welcome_path, :method=>'post') do %>
	  <%= text_field_tag('nombre', value = nil, options = {})%>
	  <%= submit_tag(value = "Empezar", options = {})%>
	<% end %>
</div>

app/views/solveds/_form.html.erb
<%= form_for(@solved) do |f| %>
  <% if @solved.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@solved.errors.count, "error") %> prohibited this solved from being saved:</h2>

      <ul>
      <% @solved.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pokemon %><br>
    <%= f.text_field :pokemon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/solveds/edit.html.erb
<h1>Editing Solved</h1>

<%= render 'form' %>

<%= link_to 'Show', @solved %> |
<%= link_to 'Back', solveds_path %>

app/views/solveds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Solveds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pokemon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @solveds.each do |solved| %>
      <tr>
        <td><%= solved.name %></td>
        <td><%= solved.pokemon %></td>
        <td><%= link_to 'Show', solved %></td>
        <td><%= link_to 'Edit', edit_solved_path(solved) %></td>
        <td><%= link_to 'Destroy', solved, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Solved', new_solved_path %>

app/views/solveds/new.html.erb
<h1>New Solved</h1>

<%= render 'form' %>

<%= link_to 'Back', solveds_path %>

app/views/solveds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @solved.name %>
</p>

<p>
  <strong>Pokemon:</strong>
  <%= @solved.pokemon %>
</p>

<%= link_to 'Edit', edit_solved_path(@solved) %> |
<%= link_to 'Back', solveds_path %>